SIDM-5846 CMC cookie changes and allow for external cookie site
hmcts/idam-web-public pull request #622
Opened 2021-05-21 11:56 UTC by nikola-naydenov-hmcts

Currently using google translated welsh translations.
Added properties allowing external cookie site change.

2021-05-21 12:41 UTC, jburke-idam approved these changes

2021-05-21 12:55 UTC, kremi commented on src/main/resources/application.yaml
> +  external-cookie-link:
I like this style better than the `external-contact-page` one - can we make them consistent please.

2021-05-21 12:58 UTC, kremi commented on src/main/webapp/WEB-INF/tags/wrapper.tag
> +                            <li><a href="${externalCookieLink}"><spring:message code="public.template.footer.support.link.cookies" /></a></li>
I think we should actually have a redirect from our `/cookies` to the confgured value (for reference - have a look at how the contactUs redirect is happening). 
The rationale is to keep any external links there might be to hmcts-access.service.gov.uk/cookies pointing to the right content, if we decide to stop updating that page and host it externally.

2021-05-21 12:58 UTC, kremi requested changes
What do you think about my second comment above?

2021-05-24 10:55 UTC, kremi approved these changes

2021-06-10 07:31 UTC, closed without merging